# Use the official Node.js 14 image as a base
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY ./Guide-to-Containers-with-Docker/05git-action-CI/* ./app

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory

# Expose the port the app runs on
EXPOSE 3000

# Command to run the app
CMD ["node", "server.js"]
